import type { GscRow } from "@/lib/types";

export const mockGscRows: GscRow[] = [
  {
    id: "best-csv-editors",
    pageUrl: "/best-csv-editors/",
    query: "best CSV editor",
    clicks: 86,
    previousClicks: 92,
    impressions: 4500,
    ctr: 1.9,
    position: 8.0,
  },
  {
    id: "excel-alternatives",
    pageUrl: "/excel-alternatives/",
    query: "best Excel alternatives",
    clicks: 152,
    previousClicks: 160,
    impressions: 6100,
    ctr: 2.5,
    position: 5.6,
  },
  {
    id: "convert-csv",
    pageUrl: "/convert-csv-to-excel/",
    query: "convert CSV to Excel",
    clicks: 320,
    previousClicks: 410,
    impressions: 7200,
    ctr: 4.4,
    position: 3.1,
  },
  {
    id: "data-cleaning",
    pageUrl: "/guides/data-cleaning/",
    query: "how to clean CSV data",
    clicks: 68,
    previousClicks: 75,
    impressions: 3900,
    ctr: 1.7,
    position: 12.4,
  },
  {
    id: "large-csv",
    pageUrl: "/open-large-csv-files/",
    query: "open large CSV file",
    clicks: 44,
    previousClicks: 49,
    impressions: 2100,
    ctr: 2.1,
    position: 15.0,
  },
  {
    id: "compare-csv",
    pageUrl: "/compare-csv-files/",
    query: "compare two CSV files",
    clicks: 26,
    previousClicks: 39,
    impressions: 1400,
    ctr: 1.9,
    position: 18.0,
  },
  {
    id: "csv-viewer",
    pageUrl: "/csv-viewer/",
    query: "CSV viewer online",
    clicks: 480,
    previousClicks: 492,
    impressions: 9200,
    ctr: 5.2,
    position: 2.3,
  },
  {
    id: "open-csv-mac",
    pageUrl: "/open-csv-on-mac/",
    query: "open CSV on Mac",
    clicks: 110,
    previousClicks: 105,
    impressions: 2800,
    ctr: 3.9,
    position: 6.8,
  },
  {
    id: "edit-csv-online",
    pageUrl: "/edit-csv-online/",
    query: "edit CSV online",
    clicks: 205,
    previousClicks: 198,
    impressions: 7800,
    ctr: 2.6,
    position: 4.4,
  },
];

export const mockProperty = {
  url: "https://rowlab.io/",
  label: "rowlab.io",
  permission: "Owner",
  lastSync: "Today, 9:42 AM",
};
